import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { ContentPage } from "@/components/ContentPage";
import { copy, isLocale, locales, type Locale } from "@/lib/i18n";
import { buildPageMetadata } from "@/lib/seo";

type Step={title:string;body:string;tips:string[]};
const text:Record<Locale,{title:string;intro:string;steps:Step[];limitsTitle:string;limits:string[];testedTitle:string;tested:string;cta:string}>={
 en:{title:"How Overlay Crop Works",intro:"Overlay Crop combines one fixed output frame with independent controls for every source image. This is different from a basic batch crop that cuts the same coordinates from every file.",steps:[
  {title:"1. Add up to five source images",body:"Choose JPG, PNG, or WebP files. Each file becomes a separate layer with its own position, zoom, rotation, opacity, visibility, and lock state. The selected image data is processed locally in the browser.",tips:["Use the clearest image as the reference.","Keep original files backed up.","On memory-limited phones, start with two images."]},
  {title:"2. Choose the final frame",body:"Select a preset ratio or enter exact output dimensions. The frame represents the final file shape and size. Every layer will be exported through this same frame.",tips:["Pick the destination before cropping.","Do not confuse ratio with pixel dimensions.","Use the smallest source crop to set a realistic output size."]},
  {title:"3. Build the reference composition",body:"Position the reference layer first. Decide subject scale, headroom, side margins, baseline, and horizon. Lock the layer when the composition is correct.",tips:["Portraits: start with the eye line.","Products: use the baseline and optical center.","Rooms: use fixed corners and horizon lines."]},
  {title:"4. Align the remaining layers",body:"Lower the opacity of the selected layer and compare stable landmarks. Adjust scale before fine position. You can drag with a mouse or one finger, zoom with the wheel or a two-finger pinch, and type exact values when needed.",tips:["Use two or more landmarks.","Accept real perspective or pose differences.","Restore opacity to 100% after alignment."]},
  {title:"5. Review every image separately",body:"Hide the other layers and inspect the active image at full opacity. Check all edges, orientation, transparency, sharpness, and the amount of empty space around the subject.",tips:["Look for clipped hair, hands, product corners, and shadows.","Check the output at the size where it will actually be displayed.","Do not assume a large output number means better quality."]},
  {title:"6. Export and verify",body:"Download one image or a ZIP containing all layers. Open a downloaded file outside the editor and confirm dimensions, orientation, file type, and visual quality before publishing the whole set.",tips:["Rename files clearly.","Test the actual carousel, slider, catalog, or video.","Keep the original files unchanged."]}
 ],limitsTitle:"What the tool does not do",limits:["It does not restore missing detail in a low-resolution source.","It does not correct lens perspective or pose differences automatically.","It does not permanently store or recover an editing session after the page is closed.","It does not replace platform-specific legal, identity-photo, medical, or organizational requirements."],testedTitle:"Testing and browser support",tested:"The workflow is designed for current desktop and mobile browsers with Canvas support. We test pointer drag, mouse-wheel zoom, touch drag, two-finger pinch, numeric controls, single export, and ZIP export. Very large camera files can still exceed mobile memory.",cta:"Open the editor"},
 ko:{title:"Overlay Crop 작동 방식",intro:"Overlay Crop은 하나의 고정된 출력 프레임과 사진마다 독립적인 이동·확대 기능을 결합합니다. 모든 원본의 같은 좌표를 잘라내는 일반적인 일괄 크롭과는 방식이 다릅니다.",steps:[
  {title:"1. 원본 사진을 최대 5장 추가",body:"JPG, PNG, WebP 파일을 선택하면 각각 별도 레이어가 됩니다. 사진마다 위치, 확대, 회전, 투명도, 표시와 잠금 상태를 따로 관리합니다. 선택한 사진은 브라우저에서 처리됩니다.",tips:["가장 선명한 사진을 기준으로 사용하세요.","원본은 별도로 보관하세요.","모바일에서는 우선 2장으로 테스트하세요."]},
  {title:"2. 최종 출력 프레임 선택",body:"기본 비율을 선택하거나 정확한 가로·세로 크기를 입력합니다. 이 프레임이 최종 파일의 모양과 크기를 뜻하며 모든 사진은 같은 프레임으로 저장됩니다.",tips:["게시 위치를 먼저 정하세요.","비율과 픽셀 크기를 구분하세요.","가장 작은 원본에 맞는 출력 크기를 선택하세요."]},
  {title:"3. 기준 구도 만들기",body:"기준 사진을 먼저 배치하고 피사체 크기, 머리 위 여백, 좌우 공간, 바닥선과 수평선을 정합니다. 구도가 완성되면 잠급니다.",tips:["인물은 눈높이부터 맞춥니다.","상품은 바닥선과 시각적 중심을 봅니다.","공간은 고정된 모서리와 수평선을 사용합니다."]},
  {title:"4. 나머지 레이어 정렬",body:"선택한 사진의 투명도를 낮추고 안정적인 기준점을 비교합니다. 세부 위치보다 배율을 먼저 맞추세요. 마우스·한 손가락 드래그, 휠·두 손가락 핀치와 숫자 입력을 사용할 수 있습니다.",tips:["기준점은 두 개 이상 사용하세요.","원근과 자세의 실제 차이는 인정하세요.","정렬 후 투명도를 100%로 돌리세요."]},
  {title:"5. 각 사진을 단독으로 검수",body:"다른 레이어를 숨기고 현재 사진을 불투명 상태로 확인합니다. 네 면의 잘림, 방향, 투명 배경, 선명도와 여백을 확인하세요.",tips:["머리카락, 손, 상품 모서리와 그림자를 봅니다.","실제 표시 크기로 확인합니다.","큰 출력 숫자가 곧 좋은 화질은 아닙니다."]},
  {title:"6. 저장 후 실제 파일 확인",body:"한 장 또는 전체 ZIP을 다운로드하고 편집기 밖에서 결과를 열어 크기, 방향, 파일 형식과 화질을 확인합니다.",tips:["파일 이름을 알아보기 쉽게 정리하세요.","실제 캐러셀·슬라이더·상품 목록·영상에서 테스트하세요.","원본은 덮어쓰지 마세요."]}
 ],limitsTitle:"이 도구가 하지 못하는 것",limits:["낮은 해상도 원본에 없던 세부 정보를 복원하지 않습니다.","렌즈 원근과 자세 차이를 자동으로 교정하지 않습니다.","페이지를 닫은 뒤 작업 세션을 영구 저장하거나 복구하지 않습니다.","증명사진·의료·조직별 규격을 대신 판단하지 않습니다."],testedTitle:"테스트와 브라우저 지원",tested:"Canvas를 지원하는 최신 데스크톱과 모바일 브라우저를 기준으로 마우스 드래그, 휠 확대, 터치 이동, 두 손가락 핀치, 숫자 입력, 개별 저장과 ZIP 저장을 확인합니다. 초고해상도 사진 여러 장은 모바일 메모리 한계를 넘을 수 있습니다.",cta:"편집기 열기"},
 ja:{title:"Overlay Cropの仕組み",intro:"共通の出力フレームと、画像ごとの独立した移動・拡大を組み合わせます。すべての元画像から同じ座標を切り取る単純な一括処理とは異なります。",steps:[
  {title:"1. 最大5枚を追加",body:"JPG、PNG、WebPは個別レイヤーになり、位置、拡大、回転、透明度、表示、ロックを別々に設定できます。画像はブラウザ内で処理されます。",tips:["最も鮮明な画像を基準にする。","元ファイルを保管する。","スマホでは少ない枚数から試す。"]},
  {title:"2. 最終フレームを選ぶ",body:"比率プリセットまたは正確な幅と高さを指定します。すべてのレイヤーはこの同じ形と寸法で書き出されます。",tips:["掲載先を先に決める。","比率とピクセル寸法を区別する。","最小の元画像に合う出力を選ぶ。"]},
  {title:"3. 基準構図を作る",body:"基準画像で被写体の大きさ、上余白、左右余白、基準線を決め、完成したらロックします。",tips:["人物は目線。","商品は基準線と視覚中心。","部屋は固定角と水平線。"]},
  {title:"4. 残りを整列",body:"透明度を下げて安定した点を比較し、位置より倍率を先に合わせます。ドラッグ、ホイール、ピンチ、数値入力が使えます。",tips:["基準点を複数使う。","遠近や姿勢の違いを認める。","最後に不透明へ戻す。"]},
  {title:"5. 個別に確認",body:"他レイヤーを隠し、四辺、向き、透明部分、鮮明さ、余白を確認します。",tips:["髪、手、商品端、影を確認。","実際の表示サイズで見る。","大きな出力値だけを品質と考えない。"]},
  {title:"6. 書き出して検証",body:"単体またはZIPで保存し、エディター外で寸法、向き、形式、品質を確認します。",tips:["分かりやすい名前を付ける。","実際の利用画面でテストする。","元画像を上書きしない。"]}
 ],limitsTitle:"できないこと",limits:["低解像度に存在しない細部の復元。","遠近や姿勢差の自動補正。","タブ終了後の作業復元。","証明写真や組織規定の判定。"],testedTitle:"テストと対応",tested:"Canvas対応の現行ブラウザで、ドラッグ、ホイール、ピンチ、数値調整、単体保存、ZIP保存を確認します。非常に大きい画像はスマホのメモリ上限を超える場合があります。",cta:"エディターを開く"},
 es:{title:"Cómo funciona Overlay Crop",intro:"Combina un marco de salida fijo con controles independientes para cada imagen. No es un recorte por lotes que corta las mismas coordenadas de todos los archivos.",steps:[
  {title:"1. Añade hasta cinco imágenes",body:"Cada JPG, PNG o WebP se convierte en una capa con posición, zoom, rotación, opacidad, visibilidad y bloqueo propios. Los archivos se procesan localmente.",tips:["Usa la imagen más clara como referencia.","Conserva los originales.","En móvil, empieza con pocas imágenes."]},
  {title:"2. Elige el marco final",body:"Selecciona una proporción o introduce dimensiones exactas. Todas las capas se exportarán con esa misma forma y tamaño.",tips:["Decide primero el destino.","Distingue proporción y píxeles.","Respeta la fuente más pequeña."]},
  {title:"3. Crea la composición de referencia",body:"Coloca primero la referencia y decide escala, margen superior, laterales, línea base y horizonte. Bloquea la capa al terminar.",tips:["Retratos: línea de los ojos.","Productos: base y centro óptico.","Espacios: esquinas fijas y horizonte."]},
  {title:"4. Alinea las capas restantes",body:"Reduce la opacidad y compara puntos estables. Ajusta escala antes que posición. Usa arrastre, rueda, pellizco o valores numéricos.",tips:["Usa dos o más puntos.","Acepta diferencias reales de perspectiva.","Vuelve a 100% de opacidad."]},
  {title:"5. Revisa cada imagen",body:"Oculta las demás capas y comprueba bordes, orientación, transparencia, nitidez y márgenes.",tips:["Busca cabello, manos, esquinas y sombras cortadas.","Revisa al tamaño final.","Un número de salida grande no crea detalle."]},
  {title:"6. Exporta y verifica",body:"Descarga una imagen o un ZIP y abre el resultado fuera del editor para confirmar dimensiones, orientación, formato y calidad.",tips:["Nombra los archivos con claridad.","Prueba el carrusel, catálogo, deslizador o vídeo real.","No sustituyas los originales."]}
 ],limitsTitle:"Lo que la herramienta no hace",limits:["No recupera detalle inexistente.","No corrige automáticamente perspectiva o postura.","No guarda permanentemente la sesión.","No sustituye requisitos legales u organizativos."],testedTitle:"Pruebas y compatibilidad",tested:"Se comprueban arrastre, rueda, gestos táctiles, pellizco, entrada numérica, descarga individual y ZIP en navegadores actuales con Canvas. Varias fotos muy grandes pueden superar la memoria móvil.",cta:"Abrir el editor"}
};
export function generateStaticParams(){return locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;if(!isLocale(locale))return{};const t=text[locale];return buildPageMetadata({locale,key:"how-it-works",title:t.title,description:t.intro,path:"how-it-works"})}
export default async function Page({params}:{params:Promise<{locale:string}>}){const{locale}=await params;if(!isLocale(locale))notFound();const t=text[locale];return <ContentPage locale={locale}><Breadcrumbs locale={locale} items={[{name:t.title}]}/><header className="pageHero"><p className="eyebrow">HOW IT WORKS</p><h1>{t.title}</h1><p>{t.intro}</p></header><div className="detailedSteps">{t.steps.map(step=><section key={step.title}><h2>{step.title}</h2><p>{step.body}</p><ul>{step.tips.map(tip=><li key={tip}>{tip}</li>)}</ul></section>)}</div><section className="limitations"><h2>{t.limitsTitle}</h2><ul>{t.limits.map(item=><li key={item}>{item}</li>)}</ul></section><section className="testedBlock"><h2>{t.testedTitle}</h2><p>{t.tested}</p></section><div className="articleCta"><h2>{copy[locale].editorTitle}</h2><Link className="primaryCta" href={`/${locale}/editor/`}>{t.cta}</Link></div></ContentPage>}
