import type { Locale } from './i18n';

export const pageCopy: Record<Locale, any> = {
  en: {
    guidesTitle: 'Image Cropping and Comparison Guides', guidesIntro: 'Practical guides for matching image position, choosing output ratios, protecting privacy, and preparing consistent before-and-after content.', read: 'Read guide',
    howTitle: 'How Overlay Crop Works', howIntro: 'Align up to five images with one shared crop frame. Everything happens locally in your browser.', steps: [['Upload your images','Choose up to five JPG, PNG, or WEBP files.'],['Choose a crop ratio','Select a preset or enter the exact output width and height.'],['Align each layer','Lower opacity, drag, zoom, rotate, and lock each image.'],['Export matching crops','Download one image or a ZIP containing every aligned crop.']],
    faqTitle:'Frequently Asked Questions', faqs:[['Are my images uploaded?','No. Selected images are processed locally in your browser and are not sent to our server.'],['Can source images have different resolutions?','Yes. Every layer can be moved and scaled independently, while the exports share one output size.'],['Why can a small image look soft?','Exporting to larger pixel dimensions cannot recreate missing original detail.'],['Can I use the tool on mobile?','Yes. The interface is responsive, although a larger screen is more comfortable for precise alignment.'],['What is the maximum number of images?','You can work with up to five images at once.'],['Does the tool merge my images?','No. Transparency is used for alignment; each layer is exported as a separate image.']],
    aboutTitle:'About Overlay Crop', aboutBody:['Overlay Crop was created for a practical photo-editing problem: original and retouched images often need to be aligned and cropped to exactly the same frame. General image croppers usually treat every file separately, which makes before-and-after comparisons jump or shift.','The editor uses a shared crop frame and independent image controls so photographers, retouchers, designers, creators, and everyday users can prepare consistent image sets without installing desktop software.','Image files remain on the device. The website may use consent-based analytics and advertising, but the selected photos are not uploaded for editing.'],
    contactTitle:'Contact', contactBody:'Questions, bug reports, translation corrections, and partnership inquiries are welcome.', contactLabel:'Email us',
    privacyTitle:'Privacy Policy', privacyUpdated:'Last updated: June 19, 2026', privacySections:[['Local image processing','Images selected in the editor are decoded and processed in your browser. They are not uploaded to or stored on our server.'],['Technical information','Like most websites, hosting and security providers may process IP address, browser type, requested pages, timestamps, and diagnostic data.'],['Analytics and advertising','Optional analytics and advertising technologies are loaded only according to consent choices and applicable law. Google and its partners may use cookies or similar technologies when advertising is enabled.'],['Your choices','You may reject optional cookies. Where required, a Google-certified consent platform should be used for advertising consent.'],['Contact','Contact us if you have a privacy question or request.']],
    termsTitle:'Terms of Use', termsSections:[['Permitted use','You may use the tool for lawful personal or commercial image preparation. You must have permission to use the images you select.'],['Prohibited use','Do not process content that violates copyright, privacy, publicity rights, or applicable law.'],['Service availability','The tool is provided as available. Browser limitations, large files, device memory, or unsupported formats may affect performance.'],['Your files','Keep your own backups. Closing or refreshing the page may clear the current editing session.'],['Changes','Features and these terms may be updated as the service develops.']],
    cookiesTitle:'Cookie Policy', cookiesSections:[['Necessary storage','The site may store essential preferences, including your language and cookie choice.'],['Optional analytics','Analytics may be used to understand page performance and improve the editor only after the required consent.'],['Advertising','When AdSense is enabled, Google and advertising partners may use cookies or similar technologies subject to consent and local law.'],['Managing preferences','You can reject optional cookies or update preferences through the consent interface. Browser settings can also remove stored data.']]
  },
  ko: {
    guidesTitle:'이미지 크롭과 전후 비교 가이드', guidesIntro:'사진 위치 맞추기, 출력 비율 선택, 개인정보 보호, 보정 전후 콘텐츠 제작에 필요한 실용적인 검색 가이드입니다.', read:'가이드 보기',
    howTitle:'Overlay Crop 사용 방법', howIntro:'최대 5장의 사진을 하나의 공통 크롭 프레임으로 맞춥니다. 모든 처리는 브라우저 안에서 진행됩니다.', steps:[['사진 업로드','JPG, PNG, WEBP 사진을 최대 5장까지 선택합니다.'],['크롭 비율 선택','기본 비율을 선택하거나 정확한 출력 가로·세로 크기를 입력합니다.'],['각 사진 정렬','투명도를 낮추고 이동·확대·회전한 뒤 위치를 잠급니다.'],['동일한 크기로 저장','선택한 사진을 개별 저장하거나 전체 결과를 ZIP으로 받습니다.']],
    faqTitle:'자주 묻는 질문', faqs:[['사진이 서버로 업로드되나요?','아닙니다. 선택한 사진은 사용자의 브라우저에서 처리되며 편집을 위해 서버로 전송되지 않습니다.'],['원본 해상도가 서로 달라도 되나요?','네. 사진마다 위치와 크기를 독립적으로 조절하고 결과는 동일한 출력 크기로 저장할 수 있습니다.'],['작은 사진이 흐리게 보이는 이유는 무엇인가요?','원본보다 크게 저장해도 원래 없던 세부 정보가 새로 생기지는 않기 때문입니다.'],['모바일에서도 사용할 수 있나요?','가능합니다. 다만 정밀한 위치 조정은 큰 화면이 더 편리합니다.'],['사진은 최대 몇 장까지 가능한가요?','한 번에 최대 5장까지 작업할 수 있습니다.'],['겹친 사진이 한 장으로 합쳐지나요?','아닙니다. 투명도는 위치 확인용이며 각 사진은 별도의 결과물로 저장됩니다.']],
    aboutTitle:'Overlay Crop 소개', aboutBody:['Overlay Crop은 보정 전 사진과 보정 후 사진을 정확히 같은 구도로 맞추는 실제 작업 문제에서 시작했습니다. 일반적인 크롭 도구는 파일을 각각 따로 다루기 때문에 비교 화면에서 얼굴이나 배경이 튀는 문제가 생기기 쉽습니다.','이 편집기는 하나의 공통 크롭 프레임과 사진별 독립 조절 기능을 제공합니다. 사진가, 보정업체, 디자이너, 콘텐츠 제작자뿐 아니라 누구나 별도 프로그램 설치 없이 일관된 사진 세트를 만들 수 있습니다.','사진 파일은 사용자의 기기에 남습니다. 동의를 기반으로 분석이나 광고 기술이 사용될 수 있지만 선택한 사진은 편집을 위해 서버에 업로드되지 않습니다.'],
    contactTitle:'문의', contactBody:'오류 제보, 번역 수정, 기능 제안 및 제휴 문의를 보내주세요.', contactLabel:'이메일 보내기',
    privacyTitle:'개인정보처리방침', privacyUpdated:'최종 업데이트: 2026년 6월 19일', privacySections:[['브라우저 내부 이미지 처리','편집기에서 선택한 사진은 브라우저에서 해석되고 처리됩니다. 사진은 당사 서버에 업로드되거나 저장되지 않습니다.'],['기술 정보','호스팅 및 보안 제공업체는 일반적인 웹사이트 운영 과정에서 IP 주소, 브라우저 종류, 요청 페이지, 접속 시간, 오류 정보를 처리할 수 있습니다.'],['분석 및 광고','선택적 분석과 광고 기술은 사용자의 동의와 관련 법률에 따라 적용됩니다. 광고가 활성화되면 Google과 파트너가 쿠키 또는 유사 기술을 사용할 수 있습니다.'],['사용자의 선택','선택 쿠키를 거부할 수 있습니다. 필요한 지역에서는 Google 인증 동의 관리 플랫폼을 사용해야 합니다.'],['문의','개인정보 관련 문의나 요청이 있는 경우 연락해 주세요.']],
    termsTitle:'이용약관', termsSections:[['허용되는 이용','합법적인 개인 또는 상업용 이미지 준비에 사용할 수 있습니다. 선택한 이미지의 이용 권한은 사용자에게 있어야 합니다.'],['금지되는 이용','저작권, 개인정보, 초상권 또는 관련 법률을 침해하는 콘텐츠를 처리해서는 안 됩니다.'],['서비스 제공','도구는 현재 제공 가능한 상태로 제공됩니다. 브라우저 제한, 대용량 파일, 기기 메모리, 지원하지 않는 형식에 따라 성능이 달라질 수 있습니다.'],['사용자 파일','원본을 별도로 보관하세요. 페이지를 닫거나 새로고침하면 현재 작업이 사라질 수 있습니다.'],['변경','서비스 발전에 따라 기능과 약관이 변경될 수 있습니다.']],
    cookiesTitle:'쿠키 정책', cookiesSections:[['필수 저장','언어와 쿠키 선택 같은 필수 환경설정이 저장될 수 있습니다.'],['선택적 분석','필요한 동의를 받은 후 사이트 성능과 편집기 개선을 위한 분석이 사용될 수 있습니다.'],['광고','AdSense가 활성화되면 Google과 광고 파트너가 동의 및 지역 법률에 따라 쿠키 또는 유사 기술을 사용할 수 있습니다.'],['환경설정 관리','동의 화면에서 선택 쿠키를 거부하거나 설정을 변경할 수 있으며 브라우저 설정으로 저장 정보를 삭제할 수도 있습니다.']]
  },
  ja: {
    guidesTitle:'画像切り抜き・比較ガイド', guidesIntro:'位置合わせ、出力比率、プライバシー、ビフォー・アフター制作のための実用ガイドです。', read:'ガイドを読む',
    howTitle:'Overlay Cropの使い方', howIntro:'最大5枚の画像を共通の切り抜き枠で揃えます。処理はブラウザ内で行われます。', steps:[['画像を追加','JPG、PNG、WEBPを最大5枚選択します。'],['比率を選択','プリセットまたは正確な出力サイズを設定します。'],['各レイヤーを整列','透明度を下げ、移動・拡大・回転してロックします。'],['同じサイズで保存','個別保存または全画像をZIPで保存します。']],
    faqTitle:'よくある質問', faqs:[['画像はアップロードされますか？','いいえ。画像はブラウザ内で処理され、編集のためにサーバーへ送信されません。'],['解像度が異なっても使えますか？','はい。各画像を個別に移動・拡大し、同じ出力サイズで保存できます。'],['小さい画像がぼやけるのはなぜですか？','大きく書き出しても元画像にない細部は復元できないためです。'],['スマートフォンで使えますか？','はい。ただし細かな位置合わせは大きな画面の方が快適です。'],['最大何枚ですか？','同時に最大5枚までです。'],['画像は1枚に合成されますか？','いいえ。透明度は位置合わせ用で、各レイヤーは別々に保存されます。']],
    aboutTitle:'Overlay Cropについて', aboutBody:['Overlay Cropは、元画像とレタッチ後の画像を同じ構図に揃える実務上の課題から作られました。一般的な切り抜きツールでは画像を別々に扱うため、比較時に位置がずれやすくなります。','共通の切り抜き枠と画像ごとの操作により、写真家、レタッチャー、デザイナー、制作者、一般ユーザーがソフトをインストールせず一貫した画像セットを作れます。','画像ファイルは端末内に残ります。同意に基づく解析や広告が使われる場合がありますが、選択画像は編集のためにアップロードされません。'],
    contactTitle:'お問い合わせ', contactBody:'不具合、翻訳修正、機能提案、提携についてご連絡ください。', contactLabel:'メールを送る',
    privacyTitle:'プライバシーポリシー', privacyUpdated:'最終更新日：2026年6月19日', privacySections:[['ローカル画像処理','選択画像はブラウザ内で処理され、当社サーバーにアップロードまたは保存されません。'],['技術情報','ホスティングやセキュリティ事業者がIPアドレス、ブラウザ、ページ、時刻、診断情報を処理する場合があります。'],['解析と広告','任意の解析・広告技術は同意と適用法に従って利用されます。'],['利用者の選択','任意Cookieを拒否できます。必要な地域ではGoogle認定CMPを使用します。'],['連絡先','プライバシーに関する質問はお問い合わせください。']],
    termsTitle:'利用規約', termsSections:[['利用許可','合法な個人・商用の画像準備に利用できます。画像の利用権限が必要です。'],['禁止事項','著作権、プライバシー、肖像権、法令を侵害する利用は禁止です。'],['提供条件','ブラウザ、ファイル容量、端末メモリ、形式により動作が異なる場合があります。'],['ファイル管理','元ファイルは必ず保存してください。更新や終了で作業が消えることがあります。'],['変更','サービスの発展に伴い機能と規約を変更する場合があります。']],
    cookiesTitle:'Cookieポリシー', cookiesSections:[['必須保存','言語やCookie選択などの設定を保存する場合があります。'],['任意の解析','必要な同意後に改善目的の解析を利用する場合があります。'],['広告','AdSense有効時は同意と法令に基づきCookie等が使われる場合があります。'],['設定管理','同意画面またはブラウザ設定で任意Cookieを管理できます。']]
  },
  es: {
    guidesTitle:'Guías de recorte y comparación de imágenes', guidesIntro:'Guías prácticas para alinear fotos, elegir proporciones, proteger la privacidad y crear contenido de antes y después.', read:'Leer guía',
    howTitle:'Cómo funciona Overlay Crop', howIntro:'Alinea hasta cinco imágenes con un marco compartido. Todo se procesa localmente en el navegador.', steps:[['Sube tus imágenes','Selecciona hasta cinco archivos JPG, PNG o WEBP.'],['Elige la proporción','Usa un formato predefinido o introduce el ancho y alto exactos.'],['Alinea cada capa','Ajusta opacidad, posición, zoom y rotación, y bloquea la capa.'],['Exporta recortes iguales','Descarga una imagen o un ZIP con todos los recortes.']],
    faqTitle:'Preguntas frecuentes', faqs:[['¿Se suben mis imágenes?','No. Se procesan localmente en el navegador y no se envían a nuestro servidor.'],['¿Pueden tener resoluciones diferentes?','Sí. Cada capa se mueve y escala por separado, pero todas se exportan con el mismo tamaño.'],['¿Por qué una imagen pequeña se ve suave?','Aumentar las dimensiones no puede recuperar detalles que no existen en el original.'],['¿Funciona en móvil?','Sí, aunque una pantalla grande facilita la alineación precisa.'],['¿Cuál es el máximo?','Hasta cinco imágenes al mismo tiempo.'],['¿Se fusionan las imágenes?','No. La transparencia solo sirve para alinear; cada capa se exporta por separado.']],
    aboutTitle:'Acerca de Overlay Crop', aboutBody:['Overlay Crop nació de un problema real de edición: las fotos originales y retocadas deben compartir exactamente el mismo encuadre. Los recortadores convencionales tratan cada archivo por separado y las comparaciones pueden saltar.','El marco compartido y los controles independientes permiten a fotógrafos, retocadores, diseñadores, creadores y usuarios preparar series coherentes sin instalar software.','Los archivos permanecen en el dispositivo. El sitio puede usar analítica y publicidad con consentimiento, pero las fotos seleccionadas no se suben para editarse.'],
    contactTitle:'Contacto', contactBody:'Envíanos errores, correcciones de traducción, propuestas de funciones o consultas de colaboración.', contactLabel:'Enviar correo',
    privacyTitle:'Política de privacidad', privacyUpdated:'Última actualización: 19 de junio de 2026', privacySections:[['Procesamiento local','Las imágenes se procesan en el navegador y no se suben ni almacenan en nuestro servidor.'],['Información técnica','Los proveedores de alojamiento y seguridad pueden procesar IP, navegador, páginas solicitadas, fechas y datos de diagnóstico.'],['Analítica y publicidad','Las tecnologías opcionales se cargan según el consentimiento y la ley aplicable.'],['Tus opciones','Puedes rechazar cookies opcionales. Cuando sea necesario se utilizará una plataforma de consentimiento certificada por Google.'],['Contacto','Escríbenos para consultas o solicitudes de privacidad.']],
    termsTitle:'Términos de uso', termsSections:[['Uso permitido','Puedes usar la herramienta para preparación legal de imágenes personales o comerciales y debes tener permiso sobre ellas.'],['Uso prohibido','No proceses contenido que infrinja derechos de autor, privacidad, imagen o la ley.'],['Disponibilidad','El rendimiento puede variar por navegador, archivos grandes, memoria o formatos no compatibles.'],['Tus archivos','Conserva copias. Cerrar o actualizar la página puede eliminar la sesión.'],['Cambios','Las funciones y términos pueden actualizarse.']],
    cookiesTitle:'Política de cookies', cookiesSections:[['Almacenamiento necesario','Podemos guardar idioma y preferencias de consentimiento.'],['Analítica opcional','Puede utilizarse tras el consentimiento para mejorar el sitio.'],['Publicidad','Con AdSense, Google y sus socios pueden usar cookies según el consentimiento y la ley local.'],['Gestión','Puedes rechazar cookies opcionales o cambiar la configuración en el panel de consentimiento.']]
  }
};
